name: Publish Helm charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git for Publish
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: .
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Publish to GitHub Pages
        run: |
          mkdir -p .cr-index
          git stash
          git checkout gh-pages
          cp ../.cr-index/index.yaml .
          cp ../.cr-release-repo/*.tgz .
          git add .
          git commit -m "Publish charts" || echo "No changes to commit"
          git push origin gh-pages
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
